### ISSUE TITLE
error from callback _on_open, _on_message

### ISSUE THREAD

**Issue by scog** [GlassyWing/stomp_ws_py#1]
Good morning!

Attempting to use your library using the following example code:

```
#!/usr/bin/python3
import json
import time
from stomp_ws.client import Client
import logging

def print_frame(frame):
    print(json.loads(frame.body))

if __name__ == '__main__':
    LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
    logging.basicConfig(level=logging.DEBUG, format=LOG_FORMAT)

    logging.debug("### Starting up")
    time.sleep(2)

    # open transport
    client = Client("ws://10.10.1.10:80/app/spring-websocket/55/test1/websocket")

    # connect to the endpoint
    client.connect(timeout=5)

    # subscribe channel
    client.subscribe("/topic/test", callback=print_frame)

    logging.debug("### Finishing up")
    time.sleep(2)
    client.disconnect()
```

But we are receiving the following error regarding number of arguments provided on `line 111 of client.py`:

```
2020-05-20 09:01:15,533 - DEBUG - Opening web socket...
2020-05-20 09:01:15,541 - ERROR - error from callback <bound method Client._on_open of <stomp_ws.client.Client object at 0x7f7d7c8876a0>>: _on_open() takes 1 positional argument but 2 were given
  File "/usr/lib/python3/dist-packages/websocket/_app.py", line 269, in _callback
    callback(self, *args)
2020-05-20 09:01:15,542 - ERROR - error from callback <bound method Client._on_message of <stomp_ws.client.Client object at 0x7f7d7c8876a0>>: _on_message() takes 2 positional arguments but 3 were given
  File "/usr/lib/python3/dist-packages/websocket/_app.py", line 269, in _callback
    callback(self, *args)
Traceback (most recent call last):
  File "./main.py", line 43, in <module>
    client.connect(headers=session.cookies,timeout=5)
  File "/home/dscogin/workarea/stomp_ws/client.py", line 111, in connect
    self._connect(timeout)
  File "/home/dscogin/workarea/stomp_ws/client.py", line 42, in _connect
    raise TimeoutError(f"Connection to {self.url} timed out")
```

We are using `python 3.6.9` and `python3-websocket v0.44.0`. Any assistance would be appreciated. Thank you sir!

**Comment by GlassyWing** [comment]
Sorry for the late reply， the websockets lib is websocket-client==0.57.0

**Comment by lydiawho** [comment]
fyi: I am running into the same issue using the latest version (websocket-client==1.3.2) 
```
ERROR:websocket:error from callback <bound method Client._on_open of <stomp_ws.client.Client object at 0x766d61c0>>: _on_open() takes 1 positional argument but 2 were given
ERROR:websocket:error from callback <bound method Client._on_error of <stomp_ws.client.Client object at 0x766d61c0>>: _on_error() takes 2 positional arguments but 3 were given
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/websocket/_app.py", line 424, in _callback
    callback(self, *args)
TypeError: _on_open() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/websocket/_app.py", line 336, in run_forever
    self._callback(self.on_open)
  File "/home/pi/.local/lib/python3.9/site-packages/websocket/_app.py", line 429, in _callback
    self.on_error(self, e)
TypeError: _on_error() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/websocket/_app.py", line 424, in _callback
    callback(self, *args)
TypeError: _on_error() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/websocket/_app.py", line 386, in run_forever
    self._callback(self.on_error, e)
  File "/home/pi/.local/lib/python3.9/site-packages/websocket/_app.py", line 429, in _callback
    self.on_error(self, e)
TypeError: _on_error() takes 2 positional arguments but 3 were given
```

**Comment by xdudin** [comment]
It seems that callback method signature in WebSocketApp from websocket-client package has been changed in [commit](https://github.com/websocket-client/websocket-client/commit/1868c7de92d9873b47977eefc9b1faf90b47c10b), so this package should be updated accordingly.

There is a [pull request](https://github.com/GlassyWing/stomp_ws_py/pull/2).
